# -*- coding: utf-8 -*-
"""Evaluating_Data_Poisoning_Attacks_TestSet_In_Training_Set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiwfqHdt99jB5ZmhPZbkNGBNBe53IIj3

#
<h1><span style="color:blue">Evaluating Data Poisoning Attacks</span></h1>

<p><em>Dataset:</em> <a href="https://huggingface.co/datasets/qualifire/prompt-injections-benchmark/viewer/default/test?row=85&views%5B%5D=test" target="_blank">Jailbreak attacks on LLMs</a></p>

#Loading the dataset

Mounts Google Drive to enable file access and persistence.
"""

# Mount Google Drive to read your dataset and save outputs
from google.colab import drive
drive.mount('/content/drive')

"""Define the path to the dataset stored on Google Drive"""

DATASET_PATH = "/content/drive/MyDrive/Evaluating_Data_Poisoning_Attacks/dataset.csv"

"""Loads the dataset and prints a few samples to inspect labels and text content"""

import pandas as pd
df = pd.read_csv(DATASET_PATH)

from textwrap import fill

pd.set_option('display.max_colwidth', None)  # niente "..."
for i, row in df.head(5).iterrows():        # cambia 10 come vuoi
    print(f"#{i}  [{row['label']}]")
    print(fill(str(row['text']), width=100)) # va a capo ogni ~100 caratteri
    print("-" * 80)

"""Displays the number of rows and columns in the dataset."""

rows, cols = df.shape
print(f"NUmber of rows: {rows} \nNumber of columns: {cols}")

"""Sets the random seed to ensure reproducibility of experiments."""

random_seed = 50

"""#Load the multiple choice jailbreak prompts"""

import pandas as pd
from google.colab import drive

# 1. Mount the drive (if you haven't already done so in this session)
drive.mount('/content/drive')

# 2. Define the exact file path
file_path = "/content/drive/MyDrive/Evaluating_Data_Poisoning_Attacks/multiple_choice_cluster.csv"

# 3. Read the CSV file and save it into the variable
multiple_choice_cluster_df = pd.read_csv(file_path)

# 4. Print the first few rows to confirm it was loaded correctly
display(multiple_choice_cluster_df.head())

"""Splits the dataset into training, validation, and test sets using stratification."""

from sklearn.model_selection import train_test_split

X = df.drop('label', axis=1)
y = df['label']

X_train_temp, X_test_val_temp, y_train, y_test_val = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=random_seed,
    stratify=y
)

X_val_temp, X_test_temp, y_val, y_test = train_test_split(
    X_test_val_temp,
    y_test_val,
    test_size=0.5,
    random_state=random_seed,
    stratify=y_test_val
)

idx_train = X_train_temp.index
idx_val = X_val_temp.index
idx_test = X_test_temp.index

print(f"--- 70% / 15% / 15% ---")
print(f"Training Set (Indexes):   {len(idx_train)} samples")
print(f"Validation Set (Indexes): {len(idx_val)} samples")
print(f"Test Set (Indexes):       {len(idx_test)} samples")

"""#training/test/validation split

##entire test set

Splits the dataset into training, validation, and test sets using stratification.
"""

from sklearn.model_selection import train_test_split

X = df.drop('label', axis=1)
y = df['label']

X_train_temp, X_test_val_temp, y_train, y_test_val = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=random_seed,
    stratify=y
)

X_val_temp, X_test_temp, y_val, y_test = train_test_split(
    X_test_val_temp,
    y_test_val,
    test_size=0.5,
    random_state=random_seed,
    stratify=y_test_val
)

idx_train = X_train_temp.index
idx_val = X_val_temp.index
idx_test = X_test_temp.index

print(f"--- 70% / 15% / 15% ---")
print(f"Training Set (Indexes):   {len(idx_train)} samples")
print(f"Validation Set (Indexes): {len(idx_val)} samples")
print(f"Test Set (Indexes):       {len(idx_test)} samples")

"""##Multiple choice prompts"""

from sklearn.model_selection import train_test_split

# 70% train, 30% temp
mc_train_df, mc_test_val_df = train_test_split(
    multiple_choice_cluster_df,
    test_size=0.3,
    random_state=random_seed
)

# 15% validation, 15% test
mc_val_df, mc_test_df = train_test_split(
    mc_test_val_df,
    test_size=0.5,
    random_state=random_seed
)

# Indexes
idx_mc_train = mc_train_df.index
idx_mc_val = mc_val_df.index
idx_mc_test = mc_test_df.index

print("--- Multiple-Choice Split: 70% / 15% / 15% ---")
print(f"Training Set:   {len(idx_mc_train)} samples")
print(f"Validation Set: {len(idx_mc_val)} samples")
print(f"Test Set:       {len(idx_mc_test)} samples")

print("Train sample:")
display(mc_train_df.head(3))

print("Validation sample:")
display(mc_val_df.head(3))

print("Test sample:")
display(mc_test_df.head(3))

"""# Attack: Copy Jailbreak Prompts from Test Set to Training Set (with Label Flip)

This attack copies jailbreak prompts (label = 1) from the **test set** into the **training set** with their label flipped to 0 (safe).

Four versions:
1. Few random jailbreak prompts from the entire test set (10%)
2. Many random jailbreak prompts from the entire test set (50%)
3. Few multiple-choice jailbreak prompts from the test set (10%)
4. Many multiple-choice jailbreak prompts from the test set (50%)

## Entire test set

### Attack function
"""

# import pandas as pd
# import numpy as np
# import math

# def copy_jailbreaks_to_train(X_train, y_train, X_test, y_test,
#                              poison_rate, jailbreak_label=1,
#                              random_seed=50):
#     """
#     Copies a fraction of jailbreak prompts (label == jailbreak_label)
#     from the test set into the training set with their label flipped to 0.
#     """
#     jb_mask = (y_test == jailbreak_label)
#     X_test_jb = X_test[jb_mask]
#     y_test_jb = y_test[jb_mask]

#     n_total  = len(X_test_jb)
#     n_poison = int(math.ceil(n_total * poison_rate)) if poison_rate > 0 else 0

#     rng = np.random.default_rng(random_seed)
#     chosen = rng.choice(X_test_jb.index.to_numpy(), size=n_poison, replace=False)

#     X_poison = X_test_jb.loc[chosen].copy()
#     y_poison = y_test_jb.loc[chosen].copy()
#     y_poison.iloc[:] = 0  # flip: jailbreak -> safe

#     X_train_out = X_train.copy()
#     X_train_out['is_poisoned'] = 0
#     X_poison = X_poison.copy()
#     X_poison['is_poisoned'] = 1

#     X_combined = pd.concat([X_train_out, X_poison], ignore_index=True)
#     y_combined = pd.concat(
#         [y_train.reset_index(drop=True), y_poison.reset_index(drop=True)],
#         ignore_index=True
#     )

#     return X_combined, y_combined, chosen

def copy_jailbreaks_to_train(X_train, y_train, X_test, y_test,
                             poison_rate, jailbreak_label=1,
                             poisoned_target_label=0,
                             random_seed=50):
    """
    Copy a fraction of jailbreak prompts from test into train with flipped label,
    preserving original row indices.

    IMPORTANT:
    - original train indices stay unchanged
    - copied test rows keep their original test indices
    - this is necessary if you later want to replace / align rows by index
    """
    jb_mask = (y_test == jailbreak_label)
    X_test_jb = X_test.loc[jb_mask].copy()
    y_test_jb = y_test.loc[jb_mask].copy()

    n_total = len(X_test_jb)
    n_poison = int(math.ceil(n_total * poison_rate)) if poison_rate > 0 else 0

    rng = np.random.default_rng(random_seed)
    chosen = rng.choice(X_test_jb.index.to_numpy(), size=n_poison, replace=False)

    X_poison = X_test_jb.loc[chosen].copy()
    y_poison = y_test_jb.loc[chosen].copy()
    y_poison.loc[:] = poisoned_target_label

    X_train_out = X_train.copy()
    if "is_poisoned" not in X_train_out.columns:
        X_train_out["is_poisoned"] = 0
    else:
        X_train_out["is_poisoned"] = X_train_out["is_poisoned"].fillna(0).astype(int)

    X_poison["is_poisoned"] = 1

    # keep original indices
    X_combined = pd.concat([X_train_out, X_poison], axis=0, sort=False)
    y_combined = pd.concat([y_train.copy(), y_poison.copy()], axis=0)

    return X_combined, y_combined, pd.Index(chosen)

"""### Poisoning rates"""

import math
FEW_RATE  = 0.10  # 10%
MANY_RATE = 0.50  # 50%

n_test_jailbreaks = int((y_test == 1).sum())
print(f'Total jailbreak prompts in test set: {n_test_jailbreaks}')
print(f'Few  ({int(FEW_RATE*100)}%): {int(math.ceil(n_test_jailbreaks * FEW_RATE))} prompts')
print(f'Many ({int(MANY_RATE*100)}%): {int(math.ceil(n_test_jailbreaks * MANY_RATE))} prompts')

"""### Version 1 - Few jailbreak prompts from test set (10%)"""

import numpy as np
X_train_v1, y_train_v1, idx_v1 = copy_jailbreaks_to_train(
    X_train_temp, y_train, X_test_temp, y_test,
    poison_rate=FEW_RATE, random_seed=random_seed
)

print(f'Version 1 - training set size: {len(X_train_v1)}')
print(f'  Poisoned samples added: {int(X_train_v1["is_poisoned"].sum())}')
print(f'  Label distribution:\n{y_train_v1.value_counts().to_string()}')

"""### Version 2 - Many jailbreak prompts from test set (50%)"""

X_train_v2, y_train_v2, idx_v2 = copy_jailbreaks_to_train(
    X_train_temp, y_train, X_test_temp, y_test,
    poison_rate=MANY_RATE, random_seed=random_seed
)

print(f'Version 2 - training set size: {len(X_train_v2)}')
print(f'  Poisoned samples added: {int(X_train_v2["is_poisoned"].sum())}')
print(f'  Label distribution:\n{y_train_v2.value_counts().to_string()}')

"""### Inspect some poisoned samples"""

from textwrap import fill

def print_poisoned_samples(X_poisoned, y_poisoned, num_samples=5):
    mask = X_poisoned['is_poisoned'] == 1
    X_p = X_poisoned[mask]
    y_p = y_poisoned[mask]
    sample = X_p.sample(n=min(num_samples, len(X_p)), random_state=42)
    for i, (idx, row) in enumerate(sample.iterrows()):
        print(f'--- Sample {i+1} | flipped label: {y_p.loc[idx]} ---')
        print(fill(str(row['text']), width=100))
        print()

print('=== Version 1 (few) - poisoned samples ===')
print_poisoned_samples(X_train_v1, y_train_v1)

"""---
## Multiple-choice jailbreak prompts
Same attack applied to the **multiple-choice** subset. Uses `true_label` instead of `label`.
"""

X_mc_train = mc_train_df.drop('true_label', axis=1)
y_mc_train = mc_train_df['true_label']

X_mc_test = mc_test_df.drop('true_label', axis=1)
y_mc_test = mc_test_df['true_label']

n_mc_test_jailbreaks = int((y_mc_test == 1).sum())
print(f'Total MC jailbreak prompts in test set: {n_mc_test_jailbreaks}')
print(f'Few  ({int(FEW_RATE*100)}%): {int(math.ceil(n_mc_test_jailbreaks * FEW_RATE))} prompts')
print(f'Many ({int(MANY_RATE*100)}%): {int(math.ceil(n_mc_test_jailbreaks * MANY_RATE))} prompts')

"""### Version 3 - Few MC jailbreak prompts from test set (10%)"""

X_mc_train_v3, y_mc_train_v3, idx_mc_v3 = copy_jailbreaks_to_train(
    X_mc_train, y_mc_train, X_mc_test, y_mc_test,
    poison_rate=FEW_RATE, random_seed=random_seed
)

print(f'Version 3 - MC training set size: {len(X_mc_train_v3)}')
print(f'  Poisoned samples added: {int(X_mc_train_v3["is_poisoned"].sum())}')
print(f'  Label distribution:\n{y_mc_train_v3.value_counts().to_string()}')

"""### Version 4 - Many MC jailbreak prompts from test set (50%)"""

X_mc_train_v4, y_mc_train_v4, idx_mc_v4 = copy_jailbreaks_to_train(
    X_mc_train, y_mc_train, X_mc_test, y_mc_test,
    poison_rate=MANY_RATE, random_seed=random_seed
)

print(f'Version 4 - MC training set size: {len(X_mc_train_v4)}')
print(f'  Poisoned samples added: {int(X_mc_train_v4["is_poisoned"].sum())}')
print(f'  Label distribution:\n{y_mc_train_v4.value_counts().to_string()}')

"""### Inspect some poisoned MC samples"""

print('=== Version 3 (few MC) - poisoned samples ===')
print_poisoned_samples(X_mc_train_v3, y_mc_train_v3)

"""---
## Summary
"""

summary = [
    ('Version 1', 'Entire test set', f'{int(FEW_RATE*100)}%',
     int(X_train_v1['is_poisoned'].sum()), len(X_train_v1)),
    ('Version 2', 'Entire test set', f'{int(MANY_RATE*100)}%',
     int(X_train_v2['is_poisoned'].sum()), len(X_train_v2)),
    ('Version 3', 'Multiple-choice', f'{int(FEW_RATE*100)}%',
     int(X_mc_train_v3['is_poisoned'].sum()), len(X_mc_train_v3)),
    ('Version 4', 'Multiple-choice', f'{int(MANY_RATE*100)}%',
     int(X_mc_train_v4['is_poisoned'].sum()), len(X_mc_train_v4)),
]

print(f'{"Version":<12}{"Subset":<20}{"Rate":<8}{"Poisoned":<12}{"Train size"}')
print('-' * 60)
for v, subset, rate, poisoned, total in summary:
    print(f'{v:<12}{subset:<20}{rate:<8}{poisoned:<12}{total}')

"""# merge multiple choice into original dataset"""

# ============================================================
# BUILD COMBINED COPY-ATTACK DATASETS CORRECTLY
# - replace clean MC rows already present in main splits
# - append copied MC test->train poisoned rows to TRAIN
# - remove those copied rows from TEST to avoid leakage duplicates
# ============================================================

import pandas as pd

def ensure_poison_col(df):
    df = df.copy()
    if "is_poisoned" not in df.columns:
        df["is_poisoned"] = 0
    else:
        df["is_poisoned"] = df["is_poisoned"].fillna(0).astype(int)
    return df

def replace_overlap_and_append_extras(df_main, df_subset, extra_idx_to_append=None):
    """
    Replace overlapping indices from df_subset into df_main.
    Optionally append extra indices from df_subset that are not in df_main.
    """
    df_out = ensure_poison_col(df_main)
    df_sub = ensure_poison_col(df_subset)

    common_idx = df_out.index.intersection(df_sub.index)
    cols_to_replace = [c for c in df_sub.columns if c in df_out.columns]

    if len(common_idx) > 0:
        df_out.loc[common_idx, cols_to_replace] = df_sub.loc[common_idx, cols_to_replace]

    if extra_idx_to_append is not None:
        extra_idx_to_append = pd.Index(extra_idx_to_append)
        extra_idx_to_append = extra_idx_to_append.intersection(df_sub.index)
        extra_idx_to_append = extra_idx_to_append.difference(df_out.index)

        if len(extra_idx_to_append) > 0:
            df_out = pd.concat([df_out, df_sub.loc[extra_idx_to_append]], axis=0, sort=False)

    return df_out.sort_index()

def build_combined_copy_attack_dataset(
    X_main_train, y_main_train,
    X_main_val, y_main_val,
    X_main_test, y_main_test,
    X_mc_train_poisoned, y_mc_train_poisoned,
    X_mc_val_clean, y_mc_val_clean,
    X_mc_test_clean, y_mc_test_clean,
    copied_from_mc_test_idx,
    label_col="label"
):
    # -----------------------
    # main labeled dfs
    # -----------------------
    train_main = X_main_train.copy()
    train_main[label_col] = y_main_train

    val_main = X_main_val.copy()
    val_main[label_col] = y_main_val

    test_main = X_main_test.copy()
    test_main[label_col] = y_main_test

    # -----------------------
    # mc labeled dfs
    # -----------------------
    train_mc = X_mc_train_poisoned.copy()
    train_mc[label_col] = y_mc_train_poisoned

    val_mc = X_mc_val_clean.copy()
    val_mc[label_col] = y_mc_val_clean

    test_mc = X_mc_test_clean.copy()
    test_mc[label_col] = y_mc_test_clean

    # TRAIN:
    # replace overlapping MC rows + append poisoned rows copied from MC test
    train_combined = replace_overlap_and_append_extras(
        train_main,
        train_mc,
        extra_idx_to_append=copied_from_mc_test_idx
    )

    # VAL:
    # just replace overlapping clean MC rows
    val_combined = replace_overlap_and_append_extras(
        val_main,
        val_mc,
        extra_idx_to_append=None
    )

    # TEST:
    # replace overlapping clean MC rows, then REMOVE the rows copied into train
    test_combined = replace_overlap_and_append_extras(
        test_main,
        test_mc,
        extra_idx_to_append=None
    )

    copied_from_mc_test_idx = pd.Index(copied_from_mc_test_idx)
    idx_to_drop_from_test = test_combined.index.intersection(copied_from_mc_test_idx)

    if len(idx_to_drop_from_test) > 0:
        test_combined = test_combined.drop(index=idx_to_drop_from_test)

    # split back into X / y
    y_train_combined = train_combined[label_col].copy()
    X_train_combined = train_combined.drop(columns=[label_col]).copy()

    y_val_combined = val_combined[label_col].copy()
    X_val_combined = val_combined.drop(columns=[label_col]).copy()

    y_test_combined = test_combined[label_col].copy()
    X_test_combined = test_combined.drop(columns=[label_col]).copy()

    return (
        X_train_combined, y_train_combined,
        X_val_combined, y_val_combined,
        X_test_combined, y_test_combined
    )

# ------------------------------------------------
# clean MC validation / test splits
# ------------------------------------------------
X_mc_val_clean = mc_val_df.drop(columns=["true_label"]).copy()
y_mc_val_clean = mc_val_df["true_label"].copy()

X_mc_test_clean = mc_test_df.drop(columns=["true_label"]).copy()
y_mc_test_clean = mc_test_df["true_label"].copy()

# ============================================================
# 10% combined copy attack
# ============================================================
(
    X_train_combined_10, y_train_combined_10,
    X_val_combined_10, y_val_combined_10,
    X_test_combined_10, y_test_combined_10
) = build_combined_copy_attack_dataset(
    X_main_train=X_train_v1,
    y_main_train=y_train_v1,
    X_main_val=X_val_temp,
    y_main_val=y_val,
    X_main_test=X_test_temp,
    y_main_test=y_test,
    X_mc_train_poisoned=X_mc_train_v3,
    y_mc_train_poisoned=y_mc_train_v3,
    X_mc_val_clean=X_mc_val_clean,
    y_mc_val_clean=y_mc_val_clean,
    X_mc_test_clean=X_mc_test_clean,
    y_mc_test_clean=y_mc_test_clean,
    copied_from_mc_test_idx=idx_mc_v3,
    label_col="label"
)

# ============================================================
# 50% combined copy attack
# ============================================================
(
    X_train_combined_50, y_train_combined_50,
    X_val_combined_50, y_val_combined_50,
    X_test_combined_50, y_test_combined_50
) = build_combined_copy_attack_dataset(
    X_main_train=X_train_v2,
    y_main_train=y_train_v2,
    X_main_val=X_val_temp,
    y_main_val=y_val,
    X_main_test=X_test_temp,
    y_main_test=y_test,
    X_mc_train_poisoned=X_mc_train_v4,
    y_mc_train_poisoned=y_mc_train_v4,
    X_mc_val_clean=X_mc_val_clean,
    y_mc_val_clean=y_mc_val_clean,
    X_mc_test_clean=X_mc_test_clean,
    y_mc_test_clean=y_mc_test_clean,
    copied_from_mc_test_idx=idx_mc_v4,
    label_col="label"
)

print("\n=== Combined copy-attack datasets ===")
print("combined_copy_attack_10 preview:")
print("Train shape:", X_train_combined_10.shape, y_train_combined_10.shape)
print("Val shape:  ", X_val_combined_10.shape, y_val_combined_10.shape)
print("Test shape: ", X_test_combined_10.shape, y_test_combined_10.shape)

print("\ncombined_copy_attack_50 preview:")
print("Train shape:", X_train_combined_50.shape, y_train_combined_50.shape)
print("Val shape:  ", X_val_combined_50.shape, y_val_combined_50.shape)
print("Test shape: ", X_test_combined_50.shape, y_test_combined_50.shape)

print("\n=== SANITY CHECK COPY ATTACK ===")

print("\ncombined_copy_attack_10")
print("Train rows:", len(X_train_combined_10))
print("Val rows:  ", len(X_val_combined_10))
print("Test rows: ", len(X_test_combined_10))
print("Poisoned in train:", int(X_train_combined_10["is_poisoned"].sum()) if "is_poisoned" in X_train_combined_10.columns else 0)
print("Poisoned in val:  ", int(X_val_combined_10["is_poisoned"].sum()) if "is_poisoned" in X_val_combined_10.columns else 0)
print("Poisoned in test: ", int(X_test_combined_10["is_poisoned"].sum()) if "is_poisoned" in X_test_combined_10.columns else 0)

print("\ncombined_copy_attack_50")
print("Train rows:", len(X_train_combined_50))
print("Val rows:  ", len(X_val_combined_50))
print("Test rows: ", len(X_test_combined_50))
print("Poisoned in train:", int(X_train_combined_50["is_poisoned"].sum()) if "is_poisoned" in X_train_combined_50.columns else 0)
print("Poisoned in val:  ", int(X_val_combined_50["is_poisoned"].sum()) if "is_poisoned" in X_val_combined_50.columns else 0)
print("Poisoned in test: ", int(X_test_combined_50["is_poisoned"].sum()) if "is_poisoned" in X_test_combined_50.columns else 0)

# import pandas as pd

# def merge_sets_by_index(X_a, y_a, X_b, y_b, label_col="label", keep="first"):
#     """
#     Merge two datasets (features + labels) and remove duplicates based on row index.
#     """
#     df_a = X_a.copy()
#     df_b = X_b.copy()

#     df_a[label_col] = y_a
#     df_b[label_col] = y_b

#     merged = pd.concat([df_a, df_b], axis=0, sort=False)

#     if "is_poisoned" not in merged.columns:
#         merged["is_poisoned"] = 0

#     merged["is_poisoned"] = merged["is_poisoned"].fillna(0).astype(int)

#     # Remove duplicated rows based on index
#     merged = merged[~merged.index.duplicated(keep=keep)]

#     y_merged = merged[label_col].copy()
#     X_merged = merged.drop(columns=[label_col]).copy()

#     return X_merged, y_merged

# import pandas as pd

# def merge_sets_by_index(X_a, y_a, X_b, y_b, label_col="label", keep="first"):
#     """
#     Merge two datasets (features + labels) and remove duplicates based on row index.
#     """
#     df_a = X_a.copy()
#     df_b = X_b.copy()

#     df_a[label_col] = y_a
#     df_b[label_col] = y_b

#     merged = pd.concat([df_a, df_b], axis=0, sort=False)

#     if "is_poisoned" not in merged.columns:
#         merged["is_poisoned"] = 0

#     merged["is_poisoned"] = merged["is_poisoned"].fillna(0).astype(int)

#     # Remove duplicated rows based on index
#     merged = merged[~merged.index.duplicated(keep=keep)]

#     y_merged = merged[label_col].copy()
#     X_merged = merged.drop(columns=[label_col]).copy()

#     return X_merged, y_merged

# # Multiple-choice CLEAN splits

# # TRAIN
# X_mc_train_clean = mc_train_df.drop(columns=["true_label"]).copy()
# y_mc_train_clean = mc_train_df["true_label"].copy()

# # VALIDATION
# X_mc_val_clean = mc_val_df.drop(columns=["true_label"]).copy()
# y_mc_val_clean = mc_val_df["true_label"].copy()

# # TEST
# X_mc_test_clean = mc_test_df.drop(columns=["true_label"]).copy()
# y_mc_test_clean = mc_test_df["true_label"].copy()

# # 10% attack: main v1 + MC v3
# X_train_combined_10, y_train_combined_10 = merge_sets_by_index(
#     X_train_v1, y_train_v1,
#     X_mc_train_v3, y_mc_train_v3,
#     label_col="label"
# )

# X_val_combined_10, y_val_combined_10 = merge_sets_by_index(
#     X_val_temp, y_val,
#     X_mc_val_clean, y_mc_val_clean,
#     label_col="label"
# )

# X_test_combined_10, y_test_combined_10 = merge_sets_by_index(
#     X_test_temp, y_test,
#     X_mc_test_clean, y_mc_test_clean,
#     label_col="label"
# )

# # 50% attack: main v2 + MC v4
# X_train_combined_50, y_train_combined_50 = merge_sets_by_index(
#     X_train_v2, y_train_v2,
#     X_mc_train_v4, y_mc_train_v4,
#     label_col="label"
# )

# X_val_combined_50, y_val_combined_50 = merge_sets_by_index(
#     X_val_temp, y_val,
#     X_mc_val_clean, y_mc_val_clean,
#     label_col="label"
# )

# X_test_combined_50, y_test_combined_50 = merge_sets_by_index(
#     X_test_temp, y_test,
#     X_mc_test_clean, y_mc_test_clean,
#     label_col="label"
# )

# # replace poisoned multiple-choice rows inside the main dataset
# import pandas as pd

# def replace_rows_by_index(X_main, y_main, X_subset, y_subset, label_col="label"):
#     """
#     Replace rows in the main dataset with rows from the poisoned subset
#     for indices that appear in both datasets.
#     """
#     df_main = X_main.copy()
#     df_subset = X_subset.copy()

#     df_main[label_col] = y_main
#     df_subset[label_col] = y_subset

#     if "is_poisoned" not in df_main.columns:
#         df_main["is_poisoned"] = 0
#     else:
#         df_main["is_poisoned"] = df_main["is_poisoned"].fillna(0).astype(int)

#     if "is_poisoned" not in df_subset.columns:
#         df_subset["is_poisoned"] = 0
#     else:
#         df_subset["is_poisoned"] = df_subset["is_poisoned"].fillna(0).astype(int)

#     common_idx = df_main.index.intersection(df_subset.index)
#     print(f"Rows replaced: {len(common_idx)}")

#     cols_to_replace = [c for c in df_subset.columns if c in df_main.columns]
#     df_main.loc[common_idx, cols_to_replace] = df_subset.loc[common_idx, cols_to_replace]

#     y_out = df_main[label_col].copy()
#     X_out = df_main.drop(columns=[label_col]).copy()

#     return X_out, y_out

# # replace poisoned multiple-choice rows inside the main dataset
# import pandas as pd

# def replace_rows_by_index(X_main, y_main, X_subset, y_subset, label_col="label"):
#     """
#     Replace rows in the main dataset with rows from the poisoned subset
#     for indices that appear in both datasets.
#     """
#     df_main = X_main.copy()
#     df_subset = X_subset.copy()

#     df_main[label_col] = y_main
#     df_subset[label_col] = y_subset

#     if "is_poisoned" not in df_main.columns:
#         df_main["is_poisoned"] = 0
#     else:
#         df_main["is_poisoned"] = df_main["is_poisoned"].fillna(0).astype(int)

#     if "is_poisoned" not in df_subset.columns:
#         df_subset["is_poisoned"] = 0
#     else:
#         df_subset["is_poisoned"] = df_subset["is_poisoned"].fillna(0).astype(int)

#     common_idx = df_main.index.intersection(df_subset.index)
#     print(f"Rows replaced: {len(common_idx)}")

#     cols_to_replace = [c for c in df_subset.columns if c in df_main.columns]
#     df_main.loc[common_idx, cols_to_replace] = df_subset.loc[common_idx, cols_to_replace]

#     y_out = df_main[label_col].copy()
#     X_out = df_main.drop(columns=[label_col]).copy()

#     return X_out, y_out

# print("\n=== Combined copy-attack datasets ===")
# print("combined_copy_attack_10 preview:")
# print("Train shape:", X_train_combined_10.shape, y_train_combined_10.shape)
# print("Val shape:  ", X_val_combined_10.shape, y_val_combined_10.shape)
# print("Test shape: ", X_test_combined_10.shape, y_test_combined_10.shape)

# print("\ncombined_copy_attack_50 preview:")
# print("Train shape:", X_train_combined_50.shape, y_train_combined_50.shape)
# print("Val shape:  ", X_val_combined_50.shape, y_val_combined_50.shape)
# print("Test shape: ", X_test_combined_50.shape, y_test_combined_50.shape)

"""#embeddings"""

# ============================================================
# BUILD COPY-ATTACK DATASETS
# - main poisoned only
# - main + multiple-choice merged
# ============================================================

datasets = {}

# ------------------------------------------------
# MAIN DATASET ONLY - 10% copy attack
# ------------------------------------------------
train_main_10 = X_train_v1.copy()
train_main_10["label"] = y_train_v1

val_main_10 = X_val_temp.copy()
val_main_10["label"] = y_val

test_main_10 = X_test_temp.copy()
test_main_10["label"] = y_test

datasets["main_copy_attack_10"] = {
    "train": train_main_10,
    "val": val_main_10,
    "test": test_main_10,
    "idx_train": train_main_10.index,
    "idx_val": val_main_10.index,
    "idx_test": test_main_10.index
}

# ------------------------------------------------
# MAIN DATASET ONLY - 50% copy attack
# ------------------------------------------------
train_main_50 = X_train_v2.copy()
train_main_50["label"] = y_train_v2

val_main_50 = X_val_temp.copy()
val_main_50["label"] = y_val

test_main_50 = X_test_temp.copy()
test_main_50["label"] = y_test

datasets["main_copy_attack_50"] = {
    "train": train_main_50,
    "val": val_main_50,
    "test": test_main_50,
    "idx_train": train_main_50.index,
    "idx_val": val_main_50.index,
    "idx_test": test_main_50.index
}

# ------------------------------------------------
# MERGED DATASET - 10% copy attack
# ------------------------------------------------
train_df_10 = X_train_combined_10.copy()
train_df_10["label"] = y_train_combined_10

val_df_10 = X_val_combined_10.copy()
val_df_10["label"] = y_val_combined_10

test_df_10 = X_test_combined_10.copy()
test_df_10["label"] = y_test_combined_10

datasets["combined_copy_attack_10"] = {
    "train": train_df_10,
    "val": val_df_10,
    "test": test_df_10,
    "idx_train": train_df_10.index,
    "idx_val": val_df_10.index,
    "idx_test": test_df_10.index
}

# ------------------------------------------------
# MERGED DATASET - 50% copy attack
# ------------------------------------------------
train_df_50 = X_train_combined_50.copy()
train_df_50["label"] = y_train_combined_50

val_df_50 = X_val_combined_50.copy()
val_df_50["label"] = y_val_combined_50

test_df_50 = X_test_combined_50.copy()
test_df_50["label"] = y_test_combined_50

datasets["combined_copy_attack_50"] = {
    "train": train_df_50,
    "val": val_df_50,
    "test": test_df_50,
    "idx_train": train_df_50.index,
    "idx_val": val_df_50.index,
    "idx_test": test_df_50.index
}

print("Datasets created successfully.")
print("Datasets available:")
for name in datasets.keys():
    print("-", name)

"""##text vectorization"""

# # ============================================================
# # STORE CURRENT SPLIT INTO A DATASET LIST
# # ============================================================

# dataset_list = {}

# dataset_list["dataset_1"] = {
#     "X": X,
#     "y": y,

#     "X_train": X_train_temp,
#     "X_val": X_val_temp,
#     "X_test": X_test_temp,
# #
#     "y_train": y_train,
#     "y_val": y_val,
#     "y_test": y_test,

#     "idx_train": idx_train,
#     "idx_val": idx_val,
#     "idx_test": idx_test
# }

# print("\nDataset stored successfully.")

# # ============================================================
# # CONVERT dataset_list INTO A SPLIT-BASED DATASET DICTIONARY
# # ============================================================

# datasets = {}

# for dataset_name, bundle in dataset_list.items():
#     train_df = bundle["X_train"].copy()
#     train_df["label"] = bundle["y_train"]

#     val_df = bundle["X_val"].copy()
#     val_df["label"] = bundle["y_val"]

#     test_df = bundle["X_test"].copy()
#     test_df["label"] = bundle["y_test"]

#     datasets[dataset_name] = {
#         "train": train_df,
#         "val": val_df,
#         "test": test_df,
#         "idx_train": bundle["idx_train"],
#         "idx_val": bundle["idx_val"],
#         "idx_test": bundle["idx_test"]
#     }

# print("dataset_list converted successfully.")

"""add datasets"""

# # ============================================================
# # BUILD ALL DATASETS IN A SINGLE SPLIT-BASED DICTIONARY
# # ============================================================

# datasets = {}

# # Main clean dataset
# datasets["main_clean"] = build_split_bundle(
#     original_df,
#     label_col="label",
#     random_seed=random_seed,
#     stratify=True
# )

# # Main poisoned datasets: word-order perturbation
# datasets["main_word_order_perturbation_10"] = build_split_bundle(
#     df_poisoned_few,
#     label_col="label",
#     random_seed=random_seed,
#     stratify=True
# )

# datasets["main_word_order_perturbation_50"] = build_split_bundle(
#     df_poisoned_many,
#     label_col="label",
#     random_seed=random_seed,
#     stratify=True
# )

# # Multiple-choice clean dataset
# datasets["multiple_choice_clean"] = build_split_bundle(
#     original_mc_df.rename(columns={"true_label": "label"}),
#     label_col="label",
#     random_seed=random_seed,
#     stratify=False
# )

# # Multiple-choice poisoned datasets: word-order perturbation
# datasets["multiple_choice_word_order_perturbation_10"] = build_split_bundle(
#     mc_poisoned_some.rename(columns={"true_label": "label"}),
#     label_col="label",
#     random_seed=random_seed,
#     stratify=False
# )

# datasets["multiple_choice_word_order_perturbation_50"] = build_split_bundle(
#     mc_poisoned_many.rename(columns={"true_label": "label"}),
#     label_col="label",
#     random_seed=random_seed,
#     stratify=False
# )

# print("Datasets created successfully.")
# print("Datasets available:")
# for name in datasets.keys():
#     print("-", name)

# # ============================================================
# # ADD BACKDOORED DATASETS TO THE SAME SPLIT-BASED DICTIONARY
# # ============================================================

# # 1) Generic backdoor datasets: 1%, 10%, 50%
# for rate in [0.01, 0.10, 0.50]:
#     split_bundle = poisoned_data[rate]
#     dataset_name = f"generic_backdoor_{int(rate * 100)}"

#     train_df = split_bundle["train"]["X"].copy()
#     train_df["label"] = split_bundle["train"]["y"]

#     val_df = split_bundle["val"]["X"].copy()
#     val_df["label"] = split_bundle["val"]["y"]

#     test_df = split_bundle["test"]["X"].copy()
#     test_df["label"] = split_bundle["test"]["y"]

#     datasets[dataset_name] = {
#         "train": train_df,
#         "val": val_df,
#         "test": test_df,
#         "idx_train": split_bundle["train"]["indices"],
#         "idx_val": split_bundle["val"]["indices"],
#         "idx_test": split_bundle["test"]["indices"]
#     }

# # 2) Multiple-choice backdoor datasets: benign-only 1%, 10%, 50%
# mc_backdoor_bundles = {
#     "multiple_choice_backdoor_1_benign_only": {
#         "train": {
#             "X": X_train_combined_benign1,
#             "y": y_train_combined_benign1,
#             "indices": idx_train_benign1
#         },
#         "val": {
#             "X": X_val_combined_benign1,
#             "y": y_val_combined_benign1,
#             "indices": idx_val_benign1
#         },
#         "test": {
#             "X": X_test_combined_benign1,
#             "y": y_test_combined_benign1,
#             "indices": idx_test_benign1
#         }
#     },
#     "multiple_choice_backdoor_10_benign_only": {
#         "train": {
#             "X": X_train_combined_benign10,
#             "y": y_train_combined_benign10,
#             "indices": idx_train_benign10
#         },
#         "val": {
#             "X": X_val_combined_benign10,
#             "y": y_val_combined_benign10,
#             "indices": idx_val_benign10
#         },
#         "test": {
#             "X": X_test_combined_benign10,
#             "y": y_test_combined_benign10,
#             "indices": idx_test_benign10
#         }
#     },
#     "multiple_choice_backdoor_50_benign_only": {
#         "train": {
#             "X": X_train_combined_benign50,
#             "y": y_train_combined_benign50,
#             "indices": idx_train_benign50
#         },
#         "val": {
#             "X": X_val_combined_benign50,
#             "y": y_val_combined_benign50,
#             "indices": idx_val_benign50
#         },
#         "test": {
#             "X": X_test_combined_benign50,
#             "y": y_test_combined_benign50,
#             "indices": idx_test_benign50
#         }
#     }
# }

# for dataset_name, mc_bundle in mc_backdoor_bundles.items():
#     train_df = mc_bundle["train"]["X"].copy()
#     train_df["label"] = mc_bundle["train"]["y"]

#     val_df = mc_bundle["val"]["X"].copy()
#     val_df["label"] = mc_bundle["val"]["y"]

#     test_df = mc_bundle["test"]["X"].copy()
#     test_df["label"] = mc_bundle["test"]["y"]

#     datasets[dataset_name] = {
#         "train": train_df,
#         "val": val_df,
#         "test": test_df,
#         "idx_train": mc_bundle["train"]["indices"],
#         "idx_val": mc_bundle["val"]["indices"],
#         "idx_test": mc_bundle["test"]["indices"]
#     }

# print("Backdoored datasets added successfully.")
# print("Datasets available:")
# for name in datasets.keys():
#     print("-", name)

# ============================================================
# TEXT PREPROCESSING FOR ALL DATASETS
# ============================================================

!pip install nltk

import nltk
import string
from itertools import islice
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, SnowballStemmer

nltk.download("words")
nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

TEXT_COL = "text"
STOP_LANG = "english"
USE_SNOWBALL = False
LOWERCASE = True

stop_set = set(stopwords.words(STOP_LANG))
punctuations = list(string.punctuation)
punct_str = "".join(punctuations)

if USE_SNOWBALL:
    stemmer = SnowballStemmer(STOP_LANG)
else:
    stemmer = PorterStemmer()

def strip_and_filter_punct(tokens):
    """
    Remove standalone punctuation and strip punctuation attached to tokens.
    """
    cleaned_tokens = []

    for tok in tokens:
        stripped_tok = tok.strip(punct_str)
        if stripped_tok and stripped_tok not in punctuations:
            cleaned_tokens.append(stripped_tok)

    return cleaned_tokens

def preprocess_split_dataframe(df, text_col="text"):
    """
    Preprocess one split dataframe and return:
    - processed dataframe
    - dictionary: row_index -> processed token list
    """
    assert text_col in df.columns, f"Column '{text_col}' not found in dataframe."

    df = df.copy()

    # Tokenize each document
    token_data = {
        idx: word_tokenize(text if isinstance(text, str) else str(text))
        for idx, text in df[text_col].items()
    }

    # Remove punctuation
    token_data = {
        idx: strip_and_filter_punct(tokens)
        for idx, tokens in token_data.items()
    }

    # Lowercase + stopword removal
    cleaned_data = {}
    for idx, tokens in token_data.items():
        if LOWERCASE:
            tokens = [t.lower() for t in tokens]

        tokens = [t for t in tokens if t not in stop_set]

        # Drop very short token lists
        cleaned_data[idx] = tokens if len(tokens) > 2 else []

    # Apply stemming
    stemmed_data = {
        idx: [stemmer.stem(token) for token in tokens]
        for idx, tokens in cleaned_data.items()
    }

    # Store processed tokens in the dataframe
    processed_series = pd.Series(stemmed_data)
    df["tokens_processed"] = df.index.map(processed_series)

    return df, stemmed_data

# This dictionary will contain processed versions of all datasets
preprocessed_datasets = {}

for dataset_name, split_bundle in datasets.items():
    preprocessed_datasets[dataset_name] = {}

    for split_name in ["train", "val", "test"]:
        df_split = split_bundle[split_name]
        df_processed, preprocessed_data = preprocess_split_dataframe(df_split, text_col=TEXT_COL)

        preprocessed_datasets[dataset_name][split_name] = {
            "df": df_processed,
            "preprocessed_data": preprocessed_data
        }

        print(f"\nProcessed dataset={dataset_name}, split={split_name}, shape={df_processed.shape}")

        # Preview a few tokenized rows
        for key, value in islice(preprocessed_data.items(), 2):
            print(f"{key}: {value}")

# ============================================================
# COUNT UNIQUE STEMS FOR EACH DATASET
# ============================================================

for dataset_name, split_bundle in preprocessed_datasets.items():
    all_stems = set()

    for split_name in ["train", "val", "test"]:
        preprocessed_data = split_bundle[split_name]["preprocessed_data"]

        for tokens in preprocessed_data.values():
            all_stems.update(tokens)

    print(f"{dataset_name} -> total unique stems: {len(all_stems)}")

# ============================================================
# BLACKLIST-BASED EXPLORATION FOR MULTIPLE DATASETS
# ============================================================

import numpy as np
from tqdm.auto import tqdm
from itertools import islice
from sklearn.metrics import classification_report
from nltk.corpus import words as nltk_words

def to_binary_label(y):
    """
    Map labels to binary format:
    jailbreak -> 1
    benign    -> 0
    """
    if isinstance(y, str):
        y = y.strip().lower()
        if y == "jailbreak":
            return 1
        elif y == "benign":
            return 0
    return int(y)

word_set = set(nltk_words.words())

blacklist_results = {}

for dataset_name, split_bundle in preprocessed_datasets.items():
    train_df = split_bundle["train"]["df"]
    val_df   = split_bundle["val"]["df"]

    train_tokens = split_bundle["train"]["preprocessed_data"]
    val_tokens   = split_bundle["val"]["preprocessed_data"]

    # Create label dictionaries
    train_labels = train_df["label"].map(to_binary_label).to_dict()
    val_labels   = val_df["label"].map(to_binary_label).to_dict()

    jailbreak_words = set()
    benign_words = set()

    # Build blacklist using the training split only
    for idx in tqdm(train_df.index, desc=f"Building blacklist - {dataset_name}"):
        stems = train_tokens.get(idx, [])
        if not stems:
            continue

        if train_labels[idx] == 1:
            jailbreak_words.update(stems)
        else:
            benign_words.update(stems)

    blacklist = jailbreak_words - benign_words
    word_blacklist = word_set.intersection(blacklist)

    # Quick inspection
    print(f"\n=== Dataset: {dataset_name} ===")
    print("Sample blacklist stems:")
    for token in islice(blacklist, 5):
        print(token)

    print(f"Blacklist size: {len(blacklist)}")
    print(f"Real-word blacklist size: {len(word_blacklist)}")

    # Evaluate on validation split
    tp = fp = tn = fn = 0
    y_true_val = []
    y_pred_val = []

    for idx in tqdm(val_df.index, desc=f"Evaluating blacklist - {dataset_name}"):
        true_label = val_labels[idx]
        stems = val_tokens.get(idx, [])

        pred_label = 1 if stems and (set(stems) & blacklist) else 0

        y_true_val.append(true_label)
        y_pred_val.append(pred_label)

        if pred_label == 1 and true_label == 1:
            tp += 1
        elif pred_label == 1 and true_label == 0:
            fp += 1
        elif pred_label == 0 and true_label == 1:
            fn += 1
        else:
            tn += 1

    blacklist_results[dataset_name] = {
        "blacklist": blacklist,
        "word_blacklist": word_blacklist,
        "y_true_val": y_true_val,
        "y_pred_val": y_pred_val
    }

    print("\nConfusion Matrix (validation):")
    print(f"| TP {tp:5d} | FN {fn:5d} |")
    print(f"| FP {fp:5d} | TN {tn:5d} |")

    print("\nClassification Report (validation):")
    print(classification_report(
        y_true_val,
        y_pred_val,
        target_names=["benign", "jailbreak"]
    ))

# ============================================================
# RANDOM BASELINE FOR EACH DATASET
# ============================================================

random_seed = 50
rng = np.random.default_rng(random_seed)

def evaluate_predictions(y_true, y_pred, title):
    tp = np.sum((y_true == 1) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))

    acc = (tp + tn) / len(y_true)
    prec = tp / (tp + fp) if (tp + fp) else 0.0
    rec = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * prec * rec / (prec + rec) if (prec + rec) else 0.0
    spec = tn / (tn + fp) if (tn + fp) else 0.0

    print(f"\n=== {title} ===")
    print("Counts:")
    print(f"TP: {tp}")
    print(f"FN: {fn}")
    print(f"FP: {fp}")
    print(f"TN: {tn}")

    print("\nConfusion matrix (rows=true, cols=pred):")
    print(f"| TP {tp:5d} | FN {fn:5d} |")
    print(f"| FP {fp:5d} | TN {tn:5d} |")

    print("\nMetrics:")
    print(f"Accuracy:    {acc:.5f}")
    print(f"Precision:   {prec:.5f}")
    print(f"Recall:      {rec:.5f}")
    print(f"F1 score:    {f1:.5f}")
    print(f"Specificity: {spec:.5f}")

for dataset_name, split_bundle in preprocessed_datasets.items():
    train_df = split_bundle["train"]["df"]
    val_df   = split_bundle["val"]["df"]

    y_train_binary = train_df["label"].map(to_binary_label).values
    y_val_binary   = val_df["label"].map(to_binary_label).values

    p_pos_train = y_train_binary.mean()
    print(f"\nDataset: {dataset_name}")
    print(f"Positive class prevalence in training: {p_pos_train:.5f}")

    y_pred_rand_strat = (rng.random(len(y_val_binary)) < p_pos_train).astype(int)

    evaluate_predictions(
        y_val_binary,
        y_pred_rand_strat,
        f"Random classifier (stratified) - {dataset_name}"
    )

# ============================================================
# LOAD OR INITIALIZE DENSE EMBEDDINGS STORAGE
# ============================================================

import pickle
import os

DRIVE_BASE_PATH = "/content/drive/MyDrive/Evaluating_Data_Poisoning_Attacks"
# FILENAME = "original+backdoor_embeddings.pkl"
# FILENAME = "word_order_perturbation_embeddings.pkl"
#FILENAME = "label_flipping_embeddings.pkl"
FILENAME = "testset_in_trainingset.pkl"
LOAD_PATH = os.path.join(DRIVE_BASE_PATH, FILENAME)

loading_ok = False

try:
    with open(LOAD_PATH, "rb") as f:
        all_embeddings = pickle.load(f)

    print("Embedding dictionary loaded successfully from Drive.")
    loading_ok = True

except FileNotFoundError:
    print(f"File not found at: {LOAD_PATH}")
    all_embeddings = {}

except Exception as e:
    print(f"Error while loading embeddings: {e}")
    all_embeddings = {}

# Ensure all datasets exist in the dictionary
for dataset_name in datasets.keys():
    if dataset_name not in all_embeddings:
        all_embeddings[dataset_name] = {
            "train": {},
            "val": {},
            "test": {},
            "vectorizers": {}
        }

print(f"Loading status: {loading_ok}")

# ============================================================
# BAG-OF-WORDS VECTORIZATION FOR ALL PRE-SPLIT DATASETS
# ============================================================

from sklearn.feature_extraction.text import CountVectorizer

for dataset_name, split_bundle in preprocessed_datasets.items():
    if dataset_name not in all_embeddings:
        all_embeddings[dataset_name] = {
            "train": {},
            "val": {},
            "test": {},
            "vectorizers": {}
        }

    if "vectorizers" not in all_embeddings[dataset_name]:
        all_embeddings[dataset_name]["vectorizers"] = {}

    train_tokens = split_bundle["train"]["preprocessed_data"]
    val_tokens   = split_bundle["val"]["preprocessed_data"]
    test_tokens  = split_bundle["test"]["preprocessed_data"]

    X_train_joined = [" ".join(train_tokens.get(idx, [])) for idx in split_bundle["train"]["df"].index]
    X_val_joined   = [" ".join(val_tokens.get(idx, [])) for idx in split_bundle["val"]["df"].index]
    X_test_joined  = [" ".join(test_tokens.get(idx, [])) for idx in split_bundle["test"]["df"].index]

    if "bow" not in all_embeddings[dataset_name]["train"]:
        print(f"\nComputing BoW for {dataset_name}...")

        vectorizer = CountVectorizer()

        X_train_vector = vectorizer.fit_transform(X_train_joined)
        X_val_vector   = vectorizer.transform(X_val_joined)
        X_test_vector  = vectorizer.transform(X_test_joined)

        all_embeddings[dataset_name]["train"]["bow"] = X_train_vector
        all_embeddings[dataset_name]["val"]["bow"]   = X_val_vector
        all_embeddings[dataset_name]["test"]["bow"]  = X_test_vector
        all_embeddings[dataset_name]["vectorizers"]["bow"] = vectorizer

    else:
        print(f"\nBoW already loaded for {dataset_name}.")

        X_train_vector = all_embeddings[dataset_name]["train"]["bow"]
        X_val_vector   = all_embeddings[dataset_name]["val"]["bow"]
        X_test_vector  = all_embeddings[dataset_name]["test"]["bow"]
        vectorizer     = all_embeddings[dataset_name]["vectorizers"]["bow"]

    print(f"--- Final bag-of-words vectorization: {dataset_name} ---")
    print(f"Training matrix shape:   {X_train_vector.shape}")
    print(f"Validation matrix shape: {X_val_vector.shape}")
    print(f"Test matrix shape:       {X_test_vector.shape}")
    print(f"Vocabulary size:         {len(vectorizer.vocabulary_)}")

# ============================================================
# HELPER FUNCTIONS FOR DENSE EMBEDDINGS
# ============================================================

import re
import numpy as np
from nltk.corpus import stopwords

stopwords_en = set(stopwords.words("english"))

embedding_names = ["bow","w2v", "glove_twitter", "glove_wiki", "fasttext", "sbert"]

def split_into_sentences(text):
    """
    Simple sentence splitter.
    Replace this function with your own version if you already defined one.
    """
    return re.split(r"[.!?]+", text)

def text_to_vector_w2v(text, w2v_model):
    """
    Convert a raw text string into an average Word2Vec embedding.
    """
    text = re.sub(r"\s+", " ", str(text)).strip().lower()

    sentences = split_into_sentences(text)

    tokens = []
    for sent in sentences:
        sent = re.sub(r"[^a-zA-Z]", " ", sent)
        tokens.extend(sent.split())

    tokens = [t for t in tokens if t not in stopwords_en]

    vecs = [w2v_model[w] for w in tokens if w in w2v_model.key_to_index]

    if not vecs:
        return np.zeros(w2v_model.vector_size)

    return np.mean(vecs, axis=0)

def get_avg_embedding(tokens, embedding_model, embedding_dim=50):
    """
    Compute the average embedding for a list of tokens using a GloVe-like model.
    """
    word_vectors = []

    for word in tokens:
        if word in embedding_model:
            word_vectors.append(embedding_model[word])

    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(embedding_dim)

def get_avg_embedding_fast(tokens, embedding_model):
    """
    Compute the average FastText embedding for a list of tokens.
    """
    if not tokens:
        return np.zeros(embedding_model.get_dimension())

    vectors = [embedding_model.get_word_vector(word) for word in tokens]
    return np.mean(vectors, axis=0)

# ============================================================
# LOAD / INITIALIZE EMBEDDING MODELS
# ============================================================

!pip install gensim fasttext sentence-transformers

from gensim.models import Word2Vec
import gensim.downloader as api
from sentence_transformers import SentenceTransformer
import fasttext
import os

print("Loading embedding models...")

# ---- Word2Vec (train on your data) ----
sentences = []
for dataset_name, split_bundle in preprocessed_datasets.items():
    tokens_dict = split_bundle["train"]["preprocessed_data"]
    sentences.extend([tokens for tokens in tokens_dict.values() if tokens])

model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
).wv

print("Word2Vec ready.")

# ---- GloVe ----
model_twitter = api.load("glove-twitter-50")
model_wiki = api.load("glove-wiki-gigaword-50")

print("GloVe ready.")

# ---- FastText ----
if not os.path.exists("cc.en.300.bin"):
    !wget -O cc.en.300.bin.gz http://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin.gz
    !gzip -d -f cc.en.300.bin.gz

ft_model = fasttext.load_model("cc.en.300.bin")

print("FastText ready.")

# ---- SBERT ----
sbert_model = SentenceTransformer("all-MiniLM-L12-v2")

print("SBERT ready.")

# ============================================================
# COMPUTE DENSE EMBEDDINGS FOR ALL PRE-SPLIT DATASETS
# ============================================================

from tqdm.auto import tqdm

for dataset_name, split_bundle in preprocessed_datasets.items():
    print("\n" + "=" * 60)
    print(f"Processing dense embeddings for dataset: {dataset_name}")
    print("=" * 60)

    for split_name in ["train", "val", "test"]:
        df_split = split_bundle[split_name]["df"]
        token_data = split_bundle[split_name]["preprocessed_data"]

        texts = df_split["text"].astype(str).tolist()
        idx_list = df_split.index.tolist()
        token_lists = [token_data.get(idx, []) for idx in idx_list]

        # ------------------------------------------------
        # 1. Word2Vec
        # ------------------------------------------------
        if "w2v" not in all_embeddings[dataset_name][split_name]:
            print(f"Computing Word2Vec for {dataset_name} - {split_name}...")

            X_w2v = np.vstack([
                text_to_vector_w2v(df_split.loc[idx, "text"], model)
                for idx in tqdm(idx_list, desc=f"{dataset_name} - {split_name} - W2V")
            ])

            all_embeddings[dataset_name][split_name]["w2v"] = X_w2v

        # ------------------------------------------------
        # 2. GloVe Twitter
        # ------------------------------------------------
        if "glove_twitter" not in all_embeddings[dataset_name][split_name]:
            print(f"Computing GloVe Twitter for {dataset_name} - {split_name}...")

            X_glove_t = np.vstack([
                get_avg_embedding(tokens, model_twitter, embedding_dim=50)
                for tokens in tqdm(token_lists, desc=f"{dataset_name} - {split_name} - GloVe Twitter")
            ])

            all_embeddings[dataset_name][split_name]["glove_twitter"] = X_glove_t

        # ------------------------------------------------
        # 3. GloVe Wikipedia
        # ------------------------------------------------
        if "glove_wiki" not in all_embeddings[dataset_name][split_name]:
            print(f"Computing GloVe Wikipedia for {dataset_name} - {split_name}...")

            X_glove_w = np.vstack([
                get_avg_embedding(tokens, model_wiki, embedding_dim=50)
                for tokens in tqdm(token_lists, desc=f"{dataset_name} - {split_name} - GloVe Wiki")
            ])

            all_embeddings[dataset_name][split_name]["glove_wiki"] = X_glove_w

        # ------------------------------------------------
        # 4. FastText
        # ------------------------------------------------
        if "fasttext" not in all_embeddings[dataset_name][split_name]:
            print(f"Computing FastText for {dataset_name} - {split_name}...")

            X_ft = np.vstack([
                get_avg_embedding_fast(tokens, ft_model)
                for tokens in tqdm(token_lists, desc=f"{dataset_name} - {split_name} - FastText")
            ])

            all_embeddings[dataset_name][split_name]["fasttext"] = X_ft

        # ------------------------------------------------
        # 5. SBERT
        # ------------------------------------------------
        if "sbert" not in all_embeddings[dataset_name][split_name]:
            print(f"Computing SBERT for {dataset_name} - {split_name}...")

            X_sbert = sbert_model.encode(
                texts,
                convert_to_numpy=True,
                show_progress_bar=True
            )

            all_embeddings[dataset_name][split_name]["sbert"] = X_sbert

        print(f"\nCompleted embeddings for {dataset_name} - {split_name}")
        for emb_name in embedding_names:
            print(f"{emb_name}: {all_embeddings[dataset_name][split_name][emb_name].shape}")

# ============================================================
# NORMALIZE ALL DENSE EMBEDDINGS USING TRAINING STATISTICS
# ============================================================

from sklearn.preprocessing import StandardScaler

for dataset_name in all_embeddings.keys():
    print(f"\n--- Normalizing embeddings for dataset: {dataset_name} ---")

    dense_embedding_names = ["w2v", "glove_twitter", "glove_wiki", "fasttext", "sbert"]
    for emb_name in dense_embedding_names:
    # for emb_name in embedding_names:
        if emb_name not in all_embeddings[dataset_name]["train"]:
            print(f"Skipping {emb_name} for {dataset_name} because it is missing.")
            continue

        print(f"Normalizing embedding: {emb_name}")

        scaler = StandardScaler()

        X_train_norm = scaler.fit_transform(all_embeddings[dataset_name]["train"][emb_name])
        X_val_norm   = scaler.transform(all_embeddings[dataset_name]["val"][emb_name])
        X_test_norm  = scaler.transform(all_embeddings[dataset_name]["test"][emb_name])

        all_embeddings[dataset_name]["train"][emb_name] = X_train_norm
        all_embeddings[dataset_name]["val"][emb_name]   = X_val_norm
        all_embeddings[dataset_name]["test"][emb_name]  = X_test_norm

print("\nNormalization completed for all datasets.")

# ============================================================
# SAVE ALL DENSE EMBEDDINGS TO GOOGLE DRIVE
# ============================================================

import os
import pickle

DRIVE_BASE_PATH = "/content/drive/MyDrive//Evaluating_Data_Poisoning_Attacks"

if not os.path.exists(DRIVE_BASE_PATH):
    os.makedirs(DRIVE_BASE_PATH)

#FILENAME = "word_order_perturbation_embeddings.pkl"
#FILENAME = "label_flipping_embeddings.pkl"
FILENAME = "testset_in_trainingset.pkl"
SAVE_PATH = os.path.join(DRIVE_BASE_PATH, FILENAME)

print(f"Embeddings will be saved to: {SAVE_PATH}")

if os.path.exists(SAVE_PATH):
    print("\nWARNING: File already exists.")
    print("Saving is skipped to avoid accidental overwrite.")
else:
    try:
        with open(SAVE_PATH, "wb") as f:
            pickle.dump(all_embeddings, f)

        print("\nSave completed successfully.")

    except Exception as e:
        print(f"\nCritical error while saving: {e}")

"""check"""

# ============================================================
# LOAD AND VERIFY SAVED EMBEDDINGS
# ============================================================

import pickle
import os

LOAD_PATH = "/content/drive/MyDrive/Evaluating_Data_Poisoning_Attacks/testset_in_trainingset.pkl"
print(f"Loading from: {LOAD_PATH}")

if not os.path.exists(LOAD_PATH):
    print("ERROR: File not found.")
else:
    with open(LOAD_PATH, "rb") as f:
        loaded_embeddings = pickle.load(f)

    print("\nFile loaded successfully!\n")

    # Print dataset names
    print("Datasets found:")
    for name in loaded_embeddings.keys():
        print("-", name)

    # Pick one dataset to inspect
    sample_dataset = list(loaded_embeddings.keys())[0]
    print(f"\nInspecting dataset: {sample_dataset}")

    for split in ["train", "val", "test"]:
        print(f"\n--- {split.upper()} ---")
        for emb_name, matrix in loaded_embeddings[sample_dataset][split].items():
            print(f"{emb_name}: shape = {matrix.shape}")